import 'dart:math';

import '../constants/game_constants.dart';

class PromoSceneDefinition {
  const PromoSceneDefinition({
    required this.id,
    required this.level,
    required this.snake,
    required this.direction,
    required this.food,
    required this.mouse,
    required this.score,
    this.started = true,
    this.showGameOver = false,
    this.bonusAt,
    this.mouseBonus = false,
    this.autoPlay = false,
    this.demoTurns = const {},
  });

  final String id;
  final GameLevel level;
  final List<Point<int>> snake;
  final Direction direction;
  final Point<int> food;
  final Point<int> mouse;
  final int score;
  final bool started;
  final bool showGameOver;
  final Point<int>? bonusAt;
  final bool mouseBonus;
  final bool autoPlay;
  final Map<int, Direction> demoTurns;

  static PromoSceneDefinition byId(String id) => all.firstWhere(
        (scene) => scene.id == id,
        orElse: () => longSnake,
      );

  static const cleanStart = PromoSceneDefinition(
    id: 'clean-start',
    level: GameLevel.meadow,
    snake: [Point(10, 8), Point(9, 8), Point(8, 8)],
    direction: Direction.right,
    food: Point(15, 7),
    mouse: Point(4, 4),
    score: 0,
    started: false,
  );

  static const earlyGameplay = PromoSceneDefinition(
    id: 'early-gameplay',
    level: GameLevel.meadow,
    snake: [
      Point(13, 7),
      Point(12, 7),
      Point(11, 7),
      Point(10, 7),
      Point(9, 7),
      Point(8, 7),
    ],
    direction: Direction.right,
    food: Point(16, 7),
    mouse: Point(4, 11),
    score: 30,
  );

  static const mediumSnake = PromoSceneDefinition(
    id: 'medium-snake',
    level: GameLevel.livingRoom,
    snake: [
      Point(14, 8),
      Point(13, 8),
      Point(12, 8),
      Point(11, 8),
      Point(10, 8),
      Point(9, 8),
      Point(9, 9),
      Point(9, 10),
      Point(10, 10),
      Point(11, 10),
      Point(12, 10),
      Point(13, 10),
      Point(14, 10),
      Point(14, 11),
      Point(14, 12),
    ],
    direction: Direction.right,
    food: Point(15, 8),
    mouse: Point(7, 12),
    score: 160,
  );

  static const longSnake = PromoSceneDefinition(
    id: 'long-snake',
    level: GameLevel.garden,
    snake: [
      Point(19, 8),
      Point(18, 8),
      Point(17, 8),
      Point(16, 8),
      Point(15, 8),
      Point(14, 8),
      Point(13, 8),
      Point(12, 8),
      Point(11, 8),
      Point(10, 8),
      Point(9, 8),
      Point(8, 8),
      Point(7, 8),
      Point(6, 8),
      Point(5, 8),
      Point(4, 8),
      Point(3, 8),
      Point(3, 9),
      Point(4, 9),
      Point(5, 9),
      Point(6, 9),
      Point(7, 9),
      Point(8, 9),
      Point(9, 9),
      Point(10, 9),
      Point(11, 9),
      Point(12, 9),
      Point(13, 9),
      Point(14, 9),
      Point(15, 9),
      Point(16, 9),
      Point(17, 9),
      Point(18, 9),
      Point(19, 9),
      Point(20, 9),
      Point(20, 10),
      Point(19, 10),
      Point(18, 10),
      Point(17, 10),
      Point(16, 10),
      Point(15, 10),
      Point(14, 10),
      Point(13, 10),
      Point(12, 10),
    ],
    direction: Direction.right,
    food: Point(20, 8),
    mouse: Point(7, 12),
    score: 480,
  );

  static const curveShowcase = PromoSceneDefinition(
    id: 'curve-showcase',
    level: GameLevel.meadow,
    snake: [
      Point(16, 5),
      Point(15, 5),
      Point(14, 5),
      Point(13, 5),
      Point(12, 5),
      Point(11, 5),
      Point(10, 5),
      Point(9, 5),
      Point(8, 5),
      Point(8, 6),
      Point(8, 7),
      Point(8, 8),
      Point(8, 9),
      Point(8, 10),
      Point(9, 10),
      Point(10, 10),
      Point(11, 10),
      Point(12, 10),
      Point(13, 10),
      Point(14, 10),
      Point(15, 10),
    ],
    direction: Direction.right,
    food: Point(17, 5),
    mouse: Point(12, 8),
    score: 230,
  );

  static const highScore = PromoSceneDefinition(
    id: 'high-score',
    level: GameLevel.garden,
    snake: [
      Point(19, 6),
      Point(18, 6),
      Point(17, 6),
      Point(16, 6),
      Point(15, 6),
      Point(14, 6),
      Point(13, 6),
      Point(12, 6),
      Point(12, 7),
      Point(12, 8),
      Point(13, 8),
      Point(14, 8),
      Point(15, 8),
      Point(16, 8),
      Point(17, 8),
      Point(18, 8),
      Point(19, 8),
      Point(20, 8),
      Point(20, 9),
      Point(20, 10),
      Point(19, 10),
      Point(18, 10),
      Point(17, 10),
      Point(16, 10),
      Point(15, 10),
      Point(14, 10),
      Point(13, 10),
      Point(12, 10),
      Point(12, 9),
      Point(11, 9),
      Point(10, 9),
      Point(9, 9),
      Point(8, 9),
      Point(8, 8),
      Point(8, 7),
      Point(9, 7),
      Point(10, 7),
      Point(10, 6),
      Point(9, 6),
      Point(8, 6),
      Point(7, 6),
      Point(6, 6),
    ],
    direction: Direction.right,
    food: Point(20, 6),
    mouse: Point(3, 12),
    score: 920,
  );

  static const mouseBonusScene = PromoSceneDefinition(
    id: 'mouse-bonus',
    level: GameLevel.meadow,
    snake: [
      Point(15, 7),
      Point(14, 7),
      Point(13, 7),
      Point(12, 7),
      Point(11, 7),
      Point(10, 7),
      Point(9, 7),
      Point(8, 7),
      Point(8, 8),
      Point(8, 9),
      Point(8, 10),
      Point(8, 11),
      Point(9, 11),
      Point(10, 11),
      Point(11, 11),
      Point(12, 11),
      Point(13, 11),
    ],
    direction: Direction.right,
    food: Point(18, 4),
    mouse: Point(4, 12),
    score: 260,
    bonusAt: Point(15, 7),
    mouseBonus: true,
  );

  static const gameOver = PromoSceneDefinition(
    id: 'game-over',
    level: GameLevel.livingRoom,
    snake: [
      Point(6, 5),
      Point(6, 6),
      Point(6, 7),
      Point(6, 8),
      Point(6, 9),
      Point(7, 9),
      Point(8, 9),
      Point(9, 9),
      Point(10, 9),
      Point(11, 9),
      Point(12, 9),
      Point(13, 9),
    ],
    direction: Direction.up,
    food: Point(15, 5),
    mouse: Point(9, 12),
    score: 520,
    showGameOver: true,
  );

  static const demo = PromoSceneDefinition(
    id: 'demo',
    level: GameLevel.meadow,
    snake: [
      Point(9, 4),
      Point(8, 4),
      Point(7, 4),
      Point(6, 4),
      Point(5, 4),
      Point(4, 4),
      Point(3, 4),
      Point(2, 4),
    ],
    direction: Direction.right,
    food: Point(20, 15),
    mouse: Point(1, 14),
    score: 90,
    started: false,
    autoPlay: true,
    demoTurns: {
      5: Direction.down,
      9: Direction.left,
      13: Direction.down,
      17: Direction.right,
      21: Direction.up,
      25: Direction.right,
      29: Direction.down,
    },
  );

  static const all = [
    cleanStart,
    earlyGameplay,
    mediumSnake,
    longSnake,
    curveShowcase,
    highScore,
    mouseBonusScene,
    gameOver,
    demo,
  ];
}
